import "./globals.css";

export const metadata = {
  title: "yametara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="bg-emerald-200">{children}</body>
    </html>
  );
}
