name: ci
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js version 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install dependencies
        run: npm install
      - name: esLint
        run: npm run lint
      - name: esLint
        run: npm run format
